#!/usr/bin/env bash
# Commit and push all skill-library changes with a dated message.
# Remote: https://github.com/Bannon-github/skill-library (public)
# Push auth: uses git CLI if credentials work (GH_TOKEN/GITHUB_TOKEN env, `gh auth`, or a
# credential helper). If not, it commits locally and prints the files an agent must push
# with the GitHub MCP (push_files), then re-aligns with origin via `--realign`.
set -euo pipefail
ROOT="${SKILL_LIBRARY_ROOT:-/workspace/skill-library}"
REMOTE_URL="https://github.com/Bannon-github/skill-library.git"
cd "$ROOT"
[ -d .git ] || git init -q -b main
git remote get-url origin >/dev/null 2>&1 || git remote add origin "$REMOTE_URL"
git config user.name  >/dev/null || git config user.name "Bannon-github"
git config user.email >/dev/null || git config user.email "132753265+Bannon-github@users.noreply.github.com"

# --realign: after an MCP push, adopt origin/main as history without touching the working tree
if [ "${1:-}" = "--realign" ]; then
  git fetch -q origin main && git reset -q --soft origin/main
  git status --short | head -20; echo "realigned to origin/main ($(git rev-parse --short HEAD))"; exit 0
fi

# 1) mirror Grok Bot workflows (SKILL.md files) into bot-workflows/
if [ -d /home/box/agent-data/workflows ]; then
  rm -rf bot-workflows && mkdir -p bot-workflows
  cp -a /home/box/agent-data/workflows/. bot-workflows/
fi

# 2) ignore distilled/*/agent-skill-*.json that are byte-identical to mcp-publish/skills (pure dupes)
python3 - <<'PY'
import filecmp, glob, os, re
start, end = "# >>> auto: identical distilled dupes", "# <<< auto"
dupes = []
for f in sorted(glob.glob("distilled/*/agent-skill-*.json")):
    pub = "mcp-publish/skills/" + os.path.basename(f)[len("agent-skill-"):]
    if os.path.exists(pub) and filecmp.cmp(f, pub, shallow=False):
        dupes.append(f)
gi = open(".gitignore").read()
gi = re.sub(re.escape(start) + r".*?" + re.escape(end) + r"\n?", "", gi, flags=re.S).rstrip("\n")
gi += "\n\n" + start + " (regenerated by scripts/git_sync.sh)\n" + "".join(d + "\n" for d in dupes) + end + "\n"
open(".gitignore", "w").write(gi)
PY
git rm -r -q --cached --ignore-unmatch $(git ls-files -ci --exclude-standard) >/dev/null 2>&1 || true

# 3) guard: refuse files > 5 MB and obvious secrets
big=$(git ls-files -co --exclude-standard -z | xargs -0 -r find 2>/dev/null -maxdepth 0 -type f -size +5M || true)
[ -n "$big" ] && { echo "refusing: files over 5 MB (add to .gitignore):"; echo "$big"; exit 1; }
if git ls-files -co --exclude-standard -z | xargs -0 -r grep -lIE '(gh[p]_[A-Za-z0-9]{20}|gh[o]_[A-Za-z0-9]{20}|github_[p]at_[A-Za-z0-9_]{20}|s[k]-[A-Za-z0-9]{20}|AK[I]A[0-9A-Z]{16}|xo[x][baprs]-[A-Za-z0-9-]{10}|-----BEGIN [A-Z ]*PRIVATE [K]EY-----)' 2>/dev/null; then
  echo "refusing: possible secret in files above"; exit 1
fi

# 4) commit
git add -A
if git diff --cached --quiet; then echo "nothing to commit"; else
  git commit -q -m "sync: $(TZ=America/Vancouver date '+%Y-%m-%d %H:%M %Z')"; echo "committed $(git rev-parse --short HEAD)"
fi

# 5) push (git CLI if auth works)
TOKEN="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
if [ -n "$TOKEN" ]; then
  git -c credential.helper= -c "http.extraheader=Authorization: Basic $(printf 'x-access-token:%s' "$TOKEN" | base64 -w0)" push -q origin main && { echo "pushed via git (token)"; exit 0; }
elif GIT_TERMINAL_PROMPT=0 git push -q origin main 2>/dev/null; then
  echo "pushed via git"; exit 0
fi
echo "PUSH PENDING: no git credentials on this box. Push these files with the GitHub MCP"
echo "(push_files owner=Bannon-github repo=skill-library branch=main), then run: $0 --realign"
git fetch -q origin main 2>/dev/null && git diff --name-status origin/main HEAD || git ls-files
exit 2
